import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/global/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-neutral-950 antialiased text-white font-serif ${inter.className}`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
